name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        run: node scraper.js
        timeout-minutes: 5  # Set a timeout for the scraper
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"  # Increase memory limit

      - name: Verify Data File
        run: |
          if [ ! -f "public/data.json" ]; then
            echo "Error: data.json not found in public directory"
            exit 1
          fi
          echo "Content of data.json:"
          cat public/data.json

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-screenshot
          path: debug-screenshot.png
          retention-days: 1

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 